### ISSUE TITLE
Inlined CSS absolute urls are being rebased to be relative

### ISSUE THREAD

**Issue by zavierboyd** [richardtallent/vite-plugin-singlefile#109]
When the plugin inlines CSS from the individual asset chunks the css urls are being rebased to be relative instead of left as absolute.
For example a css file like
```css
/* src/main.css */
body {
    background-image: url('/some-folder-on-root/200.jpeg');
    background-position: left top;
    background-repeat: no-repeat;
}
```

will be initially converted to a css asset
```css
/* dist/assets/page-nonce.css */
body{background-image:url(/some-folder-on-root/200.jpeg);background-position:left top;background-repeat:no-repeat}
```

and after inlining through this plugin
```html
  <style rel="stylesheet" crossorigin>body{background-image:url(./some-folder-on-root/200.jpeg);background-position:left top;background-repeat:no-repeat}</style>
```

I have an example repo that reproduces the bug.
https://github.com/zavierboyd/vite-plugin-singlefile-css-rebase-bug-repro

I don't know whether this is some accidental interaction between inlining the assets in the html file or something to do with regex.

Thanks for making this plugin 👍
